project_id = "rxlkzfllncxyxjmqlxkb"

[functions.submit-return-request]
verify_jwt = false

[functions.subscribe-newsletter]
verify_jwt = false

[functions.send-return-notification]
verify_jwt = false
